parameters:
#    tao_sistemas_ajax_grid.example.class: TaoSistemas\AjaxGridBundle\Example

services:
#    tao_sistemas_ajax_grid.example:
#        class: %tao_sistemas_ajax_grid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    tao_sistemas_ajax_grid.manager:
        class: TaoSistemas\AjaxGridBundle\Manager\GridManager
        arguments:
            - %tao_sistemas_ajax_grid.paginator.itensPerPage%
            - %tao_sistemas_ajax_grid.paginator.defaultType%